server:
  port: 9090

management:
  metrics:
    tags:
      application: backend
      instance: backend-${CF_INSTANCE_INDEX:0}
wavefront.application.name: demo
wavefront.application.service: back-end-app
